import { Platform, StyleSheet } from 'react-native';

const MC_FONT = Platform.OS === 'web' ? "'Press Start 2P', monospace" : 'monospace';
const MC_BODY = Platform.OS === 'web' ? "'VT323', monospace" : 'monospace';

export const styles = StyleSheet.create({
  // ─── Layout ───────────────────────────────────────────────
  container: {
    flex: 1,
    height: Platform.OS === 'web' ? ('100vh' as any) : '100%',
    overflow: 'hidden' as any,
    backgroundColor: Platform.OS === 'web' ? 'transparent' : '#1a120b',
  },

  // ─── Top Marquee Bar ──────────────────────────────────────
  topMarqueeBar: {
    backgroundColor: '#0f0a06',
    paddingVertical: 8,
    paddingHorizontal: 16,
    alignItems: 'center' as const,
    borderBottomWidth: 3,
    borderBottomColor: '#8b7a45',
    overflow: 'hidden' as any,
  },
  marqueeText: {
    color: '#c8a84e',
    fontSize: 10,
    fontWeight: '900' as const,
    letterSpacing: 2,
    fontFamily: MC_FONT,
  },

  // ─── Header (Navbar) ─────────────────────────────────────
  header: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    backgroundColor: '#2d1f12',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderBottomWidth: 3,
    borderBottomColor: '#8b7a45',
    flexWrap: 'wrap' as const,
    gap: 10,
  },
  brandBadge: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 10,
    backgroundColor: '#3d2b1a',
    borderWidth: 3,
    borderColor: '#8b7a45',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  brandTitle: {
    color: '#c8a84e',
    fontSize: 20,
    fontWeight: '900' as const,
    letterSpacing: 3,
    fontFamily: MC_FONT,
    textShadowColor: '#000',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 0,
  },
  brandSubtitle: {
    color: '#8b7a45',
    fontSize: 9,
    fontWeight: '900' as const,
    letterSpacing: 4,
    marginTop: 2,
    fontFamily: MC_FONT,
  },
  searchWrapper: {
    flex: 1,
    minWidth: 180,
    maxWidth: 420,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    backgroundColor: '#1a120b',
    borderWidth: 3,
    borderColor: '#5a4a2a',
    borderRadius: 4,
    paddingHorizontal: 12,
    height: 42,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    fontWeight: '700' as const,
    color: '#c8a84e',
    fontFamily: MC_BODY,
    outlineStyle: 'none' as any,
  },
  headerActions: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 8,
  },
  iconButton: {
    backgroundColor: '#3d2b1a',
    borderWidth: 2,
    borderColor: '#8b7a45',
    padding: 8,
    borderRadius: 4,
  },
  addNavBtn: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    backgroundColor: '#4a8c3f',
    borderWidth: 3,
    borderColor: '#6ab85e',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 4,
  },
  addNavBtnText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '900' as const,
    letterSpacing: 1,
    fontFamily: MC_FONT,
  },

  // ─── Main Layout (Sidebar + Content) ──────────────────────
  mainLayout: {
    flex: 1,
    flexDirection: 'row' as const,
  },

  // ─── Scroll Content ───────────────────────────────────────
  scrollContent: {
    paddingBottom: 40,
  },

  // ─── Section Headers ──────────────────────────────────────
  sectionHeader: {
    alignItems: 'center' as const,
    marginTop: 30,
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '900' as const,
    color: '#c8a84e',
    letterSpacing: 3,
    textAlign: 'center' as const,
    fontFamily: MC_FONT,
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 0,
  },
  sectionSubtitle: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: '#8b7a45',
    marginTop: 6,
    textAlign: 'center' as const,
    fontFamily: MC_BODY,
  },

  // ─── Product Grid ─────────────────────────────────────────
  productGrid: {
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    paddingTop: 20,
    paddingHorizontal: 16,
    gap: 12,
    justifyContent: 'flex-start' as const,
  },
  productCard: {
    backgroundColor: '#e8d9b0',
    borderWidth: 3,
    borderColor: '#5a4020',
    borderRadius: 6,
    overflow: 'hidden' as const,
  },
  cardImageWrapper: {
    position: 'relative' as const,
    aspectRatio: 1,
    backgroundColor: '#ffffff',
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    borderBottomWidth: 3,
    borderBottomColor: '#5a4020',
  },
  cardImage: {
    width: '80%' as any,
    height: '85%' as any,
  },
  cardBody: {
    padding: 10,
  },
  productTitle: {
    fontSize: 11,
    fontWeight: '900' as const,
    color: '#3a2818',
    minHeight: 32,
    marginBottom: 4,
    fontFamily: MC_FONT,
  },
  cardBrandText: {
    fontSize: 16,
    color: '#7a6a4a',
    fontFamily: MC_BODY,
    marginBottom: 4,
  },
  cardStarRow: {
    flexDirection: 'row' as const,
    gap: 2,
    marginBottom: 10,
  },
  cardDivider: {
    height: 2,
    backgroundColor: '#c8b788',
    marginBottom: 10,
  },
  cardBottomRow: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    marginBottom: 8,
  },
  cardPriceSection: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 6,
  },
  cardPriceText: {
    fontSize: 16,
    fontWeight: '900' as const,
    color: '#3a2818',
    fontFamily: MC_FONT,
  },
  cardActionsSection: {
    flexDirection: 'row' as const,
    gap: 6,
  },
  cardActionBtn: {
    backgroundColor: '#3d2b1a',
    borderWidth: 2,
    borderColor: '#5a4a2a',
    borderRadius: 4,
    padding: 8,
  },
  cardDeleteBtn: {
    borderColor: '#6b3030',
  },

  // ─── Add to Cart Button (on card) ─────────────────────────
  addToCartBtn: {
    backgroundColor: '#4a8c3f',
    borderWidth: 2,
    borderColor: '#6ab85e',
    borderRadius: 6,
    width: 40,
    height: 40,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },

  // ─── Stock Badge ──────────────────────────────────────────
  cardStockBadge: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 4,
    alignSelf: 'flex-start' as const,
    paddingVertical: 2,
  },
  cardStockText: {
    fontSize: 8,
    fontWeight: '900' as const,
    color: '#7a6a4a',
    fontFamily: MC_FONT,
  },

  // ─── Admin Action Overlay (hidden by default, shown on hover) ──
  adminOverlay: {
    position: 'absolute' as const,
    top: 8,
    right: 8,
    flexDirection: 'row' as const,
    gap: 4,
    zIndex: 5,
  },
  adminBtn: {
    backgroundColor: 'rgba(45, 31, 18, 0.9)',
    borderWidth: 2,
    borderColor: '#5a4a2a',
    borderRadius: 4,
    padding: 6,
  },
  adminDeleteBtn: {
    borderColor: '#8b2020',
    backgroundColor: 'rgba(60, 20, 20, 0.9)',
  },

  // ─── Old card action rows (kept for compatibility) ────────
  cardActionRow: {
    flexDirection: 'row' as const,
    gap: 8,
  },
  editBtn: {
    flex: 1,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    backgroundColor: '#3d2b1a',
    borderWidth: 1,
    borderColor: '#8b7a45',
    paddingVertical: 8,
    borderRadius: 4,
  },
  editBtnText: {
    fontSize: 9,
    fontWeight: '900' as const,
    color: '#c8a84e',
    fontFamily: MC_FONT,
  },
  deleteBtn: {
    flex: 1,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    backgroundColor: '#3d1a1a',
    borderWidth: 1,
    borderColor: '#6b3030',
    paddingVertical: 8,
    borderRadius: 4,
  },
  deleteBtnText: {
    fontSize: 9,
    fontWeight: '900' as const,
    color: '#ff6b6b',
    fontFamily: MC_FONT,
  },

  // ─── Creator / Cards ──────────────────────────────────────
  reviewsGrid: {
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    paddingHorizontal: 20,
    gap: 16,
    justifyContent: 'center' as const,
  },
  speechCard: {
    flex: 1,
    minWidth: 260,
    maxWidth: 360,
    borderWidth: 3,
    borderColor: '#5a4a2a',
    padding: 24,
    borderRadius: 6,
    backgroundColor: '#2d1f12',
  },
  quoteText: {
    fontSize: 16,
    fontWeight: '800' as const,
    color: '#c8a84e',
    lineHeight: 22,
    marginBottom: 14,
    fontFamily: MC_BODY,
  },
  userRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
  },
  userAvatar: {
    width: 36,
    height: 36,
    borderRadius: 4,
    backgroundColor: '#4a8c3f',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    marginRight: 10,
    borderWidth: 2,
    borderColor: '#6ab85e',
  },
  userAvatarText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900' as const,
    fontFamily: MC_FONT,
  },
  userName: {
    fontSize: 12,
    fontWeight: '800' as const,
    color: '#c8a84e',
    fontFamily: MC_BODY,
  },

  // ─── Footer ───────────────────────────────────────────────
  footerContainer: {
    backgroundColor: '#0f0a06',
    borderTopWidth: 3,
    borderTopColor: '#5a4a2a',
    marginTop: 40,
    padding: 30,
    alignItems: 'center' as const,
  },
  footerBrand: {
    alignItems: 'center' as const,
    marginBottom: 12,
  },
  footerTitle: {
    color: '#c8a84e',
    fontSize: 14,
    fontWeight: '900' as const,
    letterSpacing: 3,
    fontFamily: MC_FONT,
  },
  footerSubtitle: {
    color: '#8b7a45',
    fontSize: 13,
    fontWeight: '700' as const,
    marginTop: 6,
    fontFamily: MC_BODY,
  },
  footerCopy: {
    color: '#5a4a2a',
    fontSize: 12,
    fontWeight: '700' as const,
    fontFamily: MC_BODY,
  },

  // ─── Loading & Error ──────────────────────────────────────
  loadingContainer: {
    alignItems: 'center' as const,
    paddingVertical: 60,
  },
  loadingText: {
    fontSize: 10,
    fontWeight: '900' as const,
    color: '#c8a84e',
    marginTop: 12,
    letterSpacing: 2,
    fontFamily: MC_FONT,
  },
  errorContainer: {
    alignItems: 'center' as const,
    backgroundColor: '#2d1f12',
    borderWidth: 3,
    borderColor: '#8b2020',
    marginHorizontal: 20,
    padding: 30,
    borderRadius: 6,
  },
  errorTitle: {
    fontSize: 12,
    fontWeight: '900' as const,
    color: '#ff6b6b',
    marginTop: 10,
    fontFamily: MC_FONT,
  },
  errorSubtitle: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: '#8b7a45',
    marginVertical: 8,
    textAlign: 'center' as const,
    fontFamily: MC_BODY,
  },
  retryButton: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    backgroundColor: '#4a8c3f',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#6ab85e',
    marginTop: 10,
  },
  retryButtonText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '900' as const,
    fontFamily: MC_FONT,
  },

  // ─── Modals (Crafting Table) ──────────────────────────────
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.85)',
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    padding: 20,
  },
  modalContent: {
    width: '100%' as any,
    maxWidth: 480,
    maxHeight: '90%' as any,
    backgroundColor: '#2d1f12',
    borderWidth: 3,
    borderColor: '#8b7a45',
    borderRadius: 6,
    overflow: 'hidden' as const,
  },
  modalHeader: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 2,
    borderBottomColor: '#5a4a2a',
    backgroundColor: '#3d2b1a',
  },
  modalTitle: {
    fontSize: 11,
    fontWeight: '900' as const,
    color: '#c8a84e',
    letterSpacing: 2,
    fontFamily: MC_FONT,
  },
  closeBtn: {
    padding: 2,
  },
  formBody: {
    padding: 20,
  },
  fieldLabel: {
    fontSize: 9,
    fontWeight: '900' as const,
    color: '#c8a84e',
    marginBottom: 6,
    letterSpacing: 1,
    fontFamily: MC_FONT,
  },
  textInput: {
    backgroundColor: '#1a120b',
    borderWidth: 2,
    borderColor: '#5a4a2a',
    borderRadius: 4,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 17,
    fontWeight: '700' as const,
    color: '#c8a84e',
    marginBottom: 16,
    fontFamily: MC_BODY,
    outlineStyle: 'none' as any,
  },
  formRow: {
    flexDirection: 'row' as const,
    gap: 12,
  },
  modalFooter: {
    flexDirection: 'row' as const,
    gap: 12,
    padding: 16,
    borderTopWidth: 2,
    borderTopColor: '#5a4a2a',
    backgroundColor: '#3d2b1a',
  },
  cancelActionBtn: {
    flex: 1,
    backgroundColor: '#5a4a2a',
    borderWidth: 2,
    borderColor: '#8b7a45',
    paddingVertical: 12,
    borderRadius: 4,
    alignItems: 'center' as const,
  },
  cancelActionText: {
    fontSize: 10,
    fontWeight: '900' as const,
    color: '#c8a84e',
    fontFamily: MC_FONT,
  },
  saveActionBtn: {
    flex: 2,
    backgroundColor: '#4a8c3f',
    borderWidth: 2,
    borderColor: '#6ab85e',
    paddingVertical: 12,
    borderRadius: 4,
    alignItems: 'center' as const,
  },
  saveActionText: {
    fontSize: 10,
    fontWeight: '900' as const,
    color: '#FFFFFF',
    fontFamily: MC_FONT,
  },

  // ─── Coin Badge ───────────────────────────────────────────
  coinBadge: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 6,
    backgroundColor: '#3d2b1a',
    borderWidth: 2,
    borderColor: '#c8a84e',
    borderRadius: 6,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  coinIcon: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#FFD700',
    borderWidth: 2,
    borderColor: '#B8860B',
  },
  coinText: {
    fontSize: 11,
    fontWeight: '900' as const,
    color: '#FFD700',
    fontFamily: MC_FONT,
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 0,
  },
});

export default styles;
