import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  // ─── Layout ───────────────────────────────────────────────
  container: {
    flex: 1,
    height: Platform.OS === 'web' ? ('100vh' as any) : '100%',
    overflow: 'hidden' as any,
    backgroundColor: Platform.OS === 'web' ? 'transparent' : '#FF99CC',
  },

  // ─── Top Bar ──────────────────────────────────────────────
  topMarqueeBar: {
    backgroundColor: '#000000',
    paddingVertical: 6,
    paddingHorizontal: 12,
    alignItems: 'center' as const,
  },
  marqueeText: {
    color: '#FFE600',
    fontSize: 12,
    fontWeight: '900' as const,
    letterSpacing: 1,
  },

  // ─── Header ───────────────────────────────────────────────
  header: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    backgroundColor: '#FFE600',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 4,
    borderBottomColor: '#000000',
    flexWrap: 'wrap' as const,
    gap: 10,
  },
  brandBadge: {
    backgroundColor: '#FF007F',
    borderWidth: 3,
    borderColor: '#000000',
    paddingHorizontal: 14,
    paddingVertical: 4,
    transform: [{ rotate: '-2deg' }],
  },
  brandTitle: {
    color: '#FFE600',
    fontSize: 24,
    fontWeight: '900' as const,
    letterSpacing: 2,
    textShadowColor: '#000',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 0,
  },
  brandSubtitle: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '900' as const,
    letterSpacing: 3,
    marginTop: -4,
  },
  searchWrapper: {
    flex: 1,
    minWidth: 140,
    maxWidth: 400,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    backgroundColor: '#FFFFFF',
    borderWidth: 3,
    borderColor: '#000000',
    borderRadius: 8,
    paddingHorizontal: 10,
    height: 42,
  },
  searchIcon: {
    marginRight: 6,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    fontWeight: '700' as const,
    color: '#000000',
    outlineStyle: 'none' as any,
  },
  headerActions: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 10,
  },
  iconButton: {
    backgroundColor: '#00F0FF',
    borderWidth: 3,
    borderColor: '#000000',
    padding: 8,
    borderRadius: 8,
  },
  addNavBtn: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    backgroundColor: '#FF007F',
    borderWidth: 3,
    borderColor: '#000000',
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 8,
  },
  addNavBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900' as const,
    letterSpacing: 1,
  },
  scrollContent: {
    paddingBottom: 40,
  },

  // ─── Section Headers ───────────────────────────────────────
  sectionHeader: {
    alignItems: 'center' as const,
    marginTop: 40,
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  sectionTitle: {
    fontSize: 32,
    fontWeight: '900' as const,
    color: '#000000',
    letterSpacing: 2,
    textAlign: 'center' as const,
  },
  sectionSubtitle: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: '#666666',
    marginTop: 4,
    textAlign: 'center' as const,
  },

  // ─── Product Grid ──────────────────────────────────────────
  productGrid: {
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    paddingTop: 32,
    paddingHorizontal: 20,
    gap: 20,
    justifyContent: 'center' as const,
  },
  productCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 4,
    borderColor: '#000000',
    borderRadius: 16,
    overflow: 'hidden' as const,
  },
  cardHeader: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderBottomWidth: 3,
    borderBottomColor: '#000000',
  },
  cardHeaderBrand: {
    fontSize: 14,
    fontWeight: '900' as const,
    color: '#000000',
    letterSpacing: 1,
  },
  stockBadge: {
    backgroundColor: '#000000',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
  },
  stockBadgeText: {
    color: '#FFE600',
    fontSize: 10,
    fontWeight: '900' as const,
  },
  cardImageWrapper: {
    position: 'relative' as const,
    height: 220,
    backgroundColor: '#F5F5F5',
  },
  cardImage: {
    width: '100%' as any,
    height: '100%' as any,
  },
  starSticker: {
    position: 'absolute' as const,
    top: 10,
    left: 10,
    backgroundColor: '#FFE600',
    borderWidth: 2,
    borderColor: '#000000',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    transform: [{ rotate: '-8deg' }],
  },
  starStickerText: {
    fontSize: 11,
    fontWeight: '900' as const,
    color: '#000000',
  },
  cardBody: {
    padding: 16,
  },
  productTitle: {
    fontSize: 16,
    fontWeight: '900' as const,
    color: '#000000',
    minHeight: 44,
    marginBottom: 10,
  },
  priceRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    marginBottom: 14,
  },
  priceTag: {
    backgroundColor: '#00FF66',
    borderWidth: 3,
    borderColor: '#000000',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 6,
  },
  priceTagText: {
    fontSize: 18,
    fontWeight: '900' as const,
    color: '#000000',
  },
  cardActionRow: {
    flexDirection: 'row' as const,
    gap: 8,
  },
  editBtn: {
    flex: 1,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    backgroundColor: '#FFE600',
    borderWidth: 3,
    borderColor: '#000000',
    paddingVertical: 8,
    borderRadius: 6,
  },
  editBtnText: {
    fontSize: 12,
    fontWeight: '900' as const,
    color: '#000000',
  },
  deleteBtn: {
    flex: 1,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    backgroundColor: '#FF0055',
    borderWidth: 3,
    borderColor: '#000000',
    paddingVertical: 8,
    borderRadius: 6,
  },
  deleteBtnText: {
    fontSize: 12,
    fontWeight: '900' as const,
    color: '#FFFFFF',
  },

  // ─── Creator / Cards ───────────────────────────────────────
  reviewsGrid: {
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    paddingHorizontal: 20,
    gap: 16,
    justifyContent: 'center' as const,
  },
  speechCard: {
    flex: 1,
    minWidth: 260,
    maxWidth: 320,
    borderWidth: 3,
    borderColor: '#000000',
    padding: 20,
    borderRadius: 14,
  },
  quoteText: {
    fontSize: 14,
    fontWeight: '800' as const,
    color: '#000000',
    lineHeight: 20,
    marginBottom: 14,
  },
  userRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
  },
  userAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#000000',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    marginRight: 10,
  },
  userAvatarText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900' as const,
  },
  userName: {
    fontSize: 12,
    fontWeight: '800' as const,
    color: '#000000',
  },

  // ─── Footer ────────────────────────────────────────────────
  footerContainer: {
    backgroundColor: '#000000',
    borderTopWidth: 4,
    borderTopColor: '#FFE600',
    marginTop: 60,
    padding: 30,
    alignItems: 'center' as const,
  },
  footerBrand: {
    alignItems: 'center' as const,
    marginBottom: 10,
  },
  footerTitle: {
    color: '#FFE600',
    fontSize: 22,
    fontWeight: '900' as const,
    letterSpacing: 2,
  },
  footerSubtitle: {
    color: '#00F0FF',
    fontSize: 12,
    fontWeight: '700' as const,
    marginTop: 2,
  },
  footerCopy: {
    color: '#888888',
    fontSize: 11,
    fontWeight: '700' as const,
  },

  // ─── Loading & Error ───────────────────────────────────────
  loadingContainer: {
    alignItems: 'center' as const,
    paddingVertical: 60,
  },
  loadingText: {
    fontSize: 14,
    fontWeight: '900' as const,
    color: '#000000',
    marginTop: 12,
    letterSpacing: 1,
  },
  errorContainer: {
    alignItems: 'center' as const,
    backgroundColor: '#FFF0F5',
    borderWidth: 3,
    borderColor: '#000000',
    marginHorizontal: 20,
    padding: 30,
    borderRadius: 12,
  },
  errorTitle: {
    fontSize: 18,
    fontWeight: '900' as const,
    color: '#FF007F',
    marginTop: 10,
  },
  errorSubtitle: {
    fontSize: 13,
    fontWeight: '700' as const,
    color: '#444444',
    marginVertical: 8,
    textAlign: 'center' as const,
  },
  retryButton: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    backgroundColor: '#000000',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    marginTop: 10,
  },
  retryButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900' as const,
  },

  // ─── Modals ────────────────────────────────────────────────
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.75)',
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    padding: 20,
  },
  modalContent: {
    width: '100%' as any,
    maxWidth: 480,
    maxHeight: '90%' as any,
    backgroundColor: '#FFFFFF',
    borderWidth: 4,
    borderColor: '#000000',
    borderRadius: 16,
    overflow: 'hidden' as const,
  },
  modalHeader: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 3,
    borderBottomColor: '#000000',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '900' as const,
    color: '#000000',
    letterSpacing: 1,
  },
  closeBtn: {
    padding: 2,
  },
  formBody: {
    padding: 20,
  },
  fieldLabel: {
    fontSize: 12,
    fontWeight: '900' as const,
    color: '#000000',
    marginBottom: 6,
    letterSpacing: 1,
  },
  textInput: {
    backgroundColor: '#FFFDF0',
    borderWidth: 3,
    borderColor: '#000000',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    fontWeight: '700' as const,
    color: '#000000',
    marginBottom: 16,
    outlineStyle: 'none' as any,
  },
  formRow: {
    flexDirection: 'row' as const,
    gap: 12,
  },
  modalFooter: {
    flexDirection: 'row' as const,
    gap: 12,
    padding: 16,
    borderTopWidth: 3,
    borderTopColor: '#000000',
    backgroundColor: '#FFFDF0',
  },
  cancelActionBtn: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 3,
    borderColor: '#000000',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center' as const,
  },
  cancelActionText: {
    fontSize: 13,
    fontWeight: '900' as const,
    color: '#000000',
  },
  saveActionBtn: {
    flex: 2,
    backgroundColor: '#FF007F',
    borderWidth: 3,
    borderColor: '#000000',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center' as const,
  },
  saveActionText: {
    fontSize: 13,
    fontWeight: '900' as const,
    color: '#FFFFFF',
  },
});

export default styles;
